# Generated by Django 6.0.5 on 2026-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('user', 'full_name', 'phone', 'city', 'shipping_address'), name='unique_user_address'),
        ),
    ]
