# Generated by Django 6.0.5 on 2026-06-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('₽', 'RUB')], default='USD', max_length=3),
        ),
    ]
