# Generated by Django 6.0.5 on 2026-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, default='per 1 lb', help_text='Например: per 1 lb, per 100g, per pouch', max_length=50, verbose_name='Единица измерения цены'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Формат JSON: {"Origin": "USA", "Type": "Dual-Purpose", ...}', verbose_name='Технические характеристики'),
        ),
    ]
