# Generated by Django 6.0.5 on 2026-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_price_unit_product_specifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, default='per 1 lb', help_text='For example: per 1 lb, per 100g, per pouch', max_length=50, verbose_name='Price unit of measurement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Format JSON: {"Origin": "USA", "Type": "Dual-Purpose", ...}', verbose_name='Technical specifications'),
        ),
    ]
